export const LOG_IN = "LOGIN-Jira";
export const LOGIN_SAGA_API = "LOGIN_SAGA-Jira";

export const GET_USER = "GET_USER-All";
export const GET_USER_SAGA_API = "GET_USER_SAGA_API-ALL";

export const GET_CATEGORY = "GET_CATEGORY-jira";
export const GET_CATEGORY_SAGA_API = "GET_CATEGORY_SAGA-jira";

export const CREATE_PROJECT = "CREATE_PROJECT-JIRA";
export const CREATE_PROJECT_SAGA_API = "CREATE_PROJECT_SAGA_API-JIRA";

export const GET_ALL_PROJECT = "GET_ALL_PROJECT-JIRA";
export const GET_ALL_PROJECT_SAGA_API = "GET_ALL_PROJECT_SAGA_API-JIRA";

export const DELETE_PROJECT = "DELETE_PROJECT_JIRA";
export const DELETE_PROJECT_SAGA_API = "DELETE_PROJECT_SAGA_API-JIRA";

export const GET_DETAIL_PROJECT = "GET_DETAIL_PROJECT";
export const GET_DETAIL_PROJECT_SAGA_API = "GET_DETAIL_PROJECT_SAGA_API_JIRA";

export const UPDATE_PROJECT_SAGA_API = "UPDATE_PROJECT_SAGA_API-JIRA";

export const KEY_SEARCH_PROJECT = "KEY_SEARCH_PROJECT-JIRA";

export const ADD_USER_IN_PROJECT = "ADD_USER_IN_PROJECT";
export const ADD_USER_IN_PROJECT_SAGA_API = "ADD_USER_IN_PROJECT_SAGA_API-jara";

export const GET_MEMBER_BY_PROJECT_ID = "GET_MEMBER_BY_PROJECT_ID-jara";
export const GET_MEMBER_BY_PROJECT_ID_SAGA_API = "GET_MEMBER_BY_PROJECT_ID_SAGA_API-jiraSaga";

export const REMOVE_USER_FROM_PROJECT = "REMOVE_USER_FROM_PROJECT-jara";
export const REMOVE_USER_FROM_PROJECT_SAGA_API = "REMOVE_USER_FROM_PROJECT_SAGA_API-JIRA";

export const GET_ALL_PRIORITY = "GET_ALL_PRIORITY-SAGA";
export const GET_ALL_PRIORITY_SAGA_API = "GET_ALL_PRIORITY_SAGA_API-JIRA";

export const GET_ALL_TASK_TYPE = "GET_ALL_TASK_TYPE-SAGA";
export const GET_ALL_TASK_TYPE_SAGA_API = "GET_ALL_TASK_TYPE_SAGA_API-JIRA";

export const CREATE_TASK = "CREATE_TASK-JIRA";
export const CREATE_TASK_SAGA_API = "CREATE_TASK_SAGA_API-JIRA";

export const GET_ALL_STATUS = "GET_ALL_STATUS-JIRA";
export const GET_ALL_STATUS_SAGA_API = "GET_ALL_STATUS_SAGA_API-JIRA";

export const GET_TASK_DETAIL_SAGA_API = "GET_TASK_DETAIL_SAGA_API-JIRA";
export const GET_TASK_DETAIL = "GET_TASK_DETAIL-JIRA";

export const UPDATE_STATUS_SAGA_API = "UPDATE_STATUS_SAGA_API-JIRA";

export const UPDATE_PRIORITY_SAGA_API = "UPDATE_PRIORITY_SAGA_API-JIRA";
export const UPDATE_ESTIMATE_SAGA_API = "UPDATE_ESTIMATE_SAGA_API-JIRA";
export const UPDATE_TIME_TRACKING_SAGA_API = "UPDATE_TIME_TRACKING_SAGA_API-JIRA";

export const REMOVE_USER_FROM_TASK_SAGA_API = "REMOVE_USER_FROM_TASK_SAGA_API-JIRA";

export const ASSIGN_USER_TASK_SAGA_API = "ASSIGN_USER_TASK_SAGA_API-JIRA";

export const UPDATA_DESCRIPTION_SAGA_API = "UPDATA_DESCRIPTION_SAGA_API-JIRA";
export const UPDATE_TASK_SAGA_API = "UPDATE_TASK_SAGA_API-JIRA";
